# Description
# ===========
# This playbook create an Azure VM with public IP, and opens port 22 for SSH and 80 for HTTP

- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: "vmcreate001"
    vm_name: "testvm"
    location: "westeurope"
    vm_network: "testvm_network"
    vm_subnet: "testvm_subnet"
    vm_public_ip: "testvm_public_ip"
    vm_securitygroup: "testvm_securitygroup"
    vm_user: "azureuser"
    vm_password: "Password@123"
    
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
      
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_network }}"
      address_prefixes: "10.0.0.0/16"
      
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_subnet }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ vm_network }}"
      
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ vm_public_ip }}"
      domain_name_label: "{{ vm_name }}-00121"
      
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_securitygroup }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: HTTP
          protocol: Tcp
          destination_port_range: 80
          access: Allow
          priority: 1002
          direction: Inbound
          
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}-eth"
      virtual_network: "{{ vm_network }}"
      subnet: "{{ vm_subnet }}"
      public_ip_name: "{{ vm_public_ip }}"
      security_group: "{{ vm_securitygroup }}"
      
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      vm_size: Standard_DS1_v2
      admin_username: "{{ vm_user }}"
      admin_password: "{{ vm_password }}"
      # ssh key if needed
      network_interfaces: "{{ vm_name }}-eth"
      image:
        offer: CentOS
        publisher: OpenLogic # Maybe it is needed to change this for: Rogue Wave Software
        sku: '7-CI' # Maybe it is necessary to change this for the concrete version, for instance "7.6"
        version: latest
