---
- hosts: localhost

  tasks:
    - block:

      - name: Obtain SSO token
        ovirt_auth:
          url: "{{ ovirt_url }}"
          username: "{{ ovirt_username }}"
          password: "{{ ovirt_password }}"
          insecure: true

       # Detach disk from VM1
       - ovirt_disk:
           state: detached
           name: "{{ vm_disk }}"
           vm_name: rhel7
           size: 5GiB
           format: raw
           interface: virtio

       # Attach disk to VM2
       - ovirt_disk:
           state: atached
           name: "{{ my_disk }}"
           vm_name: "{{ vm2 }}"
           size: 5GiB
           format: raw
           interface: virtio


      always:
        - name: Revoke SSO token
          ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
